export type CountryOption = { code: string; es: string; en: string };

export const COUNTRIES: CountryOption[] = [
  { code: "AD", es: "Andorra", en: "Andorra" },
  { code: "AE", es: "Emiratos Árabes Unidos", en: "United Arab Emirates" },
  { code: "AG", es: "Antigua y Barbuda", en: "Antigua and Barbuda" },
  { code: "AL", es: "Albania", en: "Albania" },
  { code: "AM", es: "Armenia", en: "Armenia" },
  { code: "AO", es: "Angola", en: "Angola" },
  { code: "AR", es: "Argentina", en: "Argentina" },
  { code: "AT", es: "Austria", en: "Austria" },
  { code: "AU", es: "Australia", en: "Australia" },
  { code: "AZ", es: "Azerbaiyán", en: "Azerbaijan" },
  { code: "BA", es: "Bosnia y Herzegovina", en: "Bosnia and Herzegovina" },
  { code: "BB", es: "Barbados", en: "Barbados" },
  { code: "BD", es: "Bangladés", en: "Bangladesh" },
  { code: "BE", es: "Bélgica", en: "Belgium" },
  { code: "BF", es: "Burkina Faso", en: "Burkina Faso" },
  { code: "BG", es: "Bulgaria", en: "Bulgaria" },
  { code: "BH", es: "Baréin", en: "Bahrain" },
  { code: "BJ", es: "Benín", en: "Benin" },
  { code: "BN", es: "Brunéi", en: "Brunei" },
  { code: "BO", es: "Bolivia", en: "Bolivia" },
  { code: "BR", es: "Brasil", en: "Brazil" },
  { code: "BS", es: "Bahamas", en: "Bahamas" },
  { code: "BT", es: "Bután", en: "Bhutan" },
  { code: "BW", es: "Botsuana", en: "Botswana" },
  { code: "BY", es: "Bielorrusia", en: "Belarus" },
  { code: "BZ", es: "Belice", en: "Belize" },
  { code: "CA", es: "Canadá", en: "Canada" },
  { code: "CD", es: "Congo (RD)", en: "Congo (DR)" },
  { code: "CF", es: "Rep. Centroafricana", en: "Central African Republic" },
  { code: "CG", es: "Congo", en: "Congo" },
  { code: "CH", es: "Suiza", en: "Switzerland" },
  { code: "CI", es: "Costa de Marfil", en: "Ivory Coast" },
  { code: "CL", es: "Chile", en: "Chile" },
  { code: "CM", es: "Camerún", en: "Cameroon" },
  { code: "CN", es: "China", en: "China" },
  { code: "CO", es: "Colombia", en: "Colombia" },
  { code: "CR", es: "Costa Rica", en: "Costa Rica" },
  { code: "CU", es: "Cuba", en: "Cuba" },
  { code: "CV", es: "Cabo Verde", en: "Cape Verde" },
  { code: "CY", es: "Chipre", en: "Cyprus" },
  { code: "CZ", es: "Chequia", en: "Czech Republic" },
  { code: "DE", es: "Alemania", en: "Germany" },
  { code: "DJ", es: "Yibuti", en: "Djibouti" },
  { code: "DK", es: "Dinamarca", en: "Denmark" },
  { code: "DM", es: "Dominica", en: "Dominica" },
  { code: "DO", es: "Rep. Dominicana", en: "Dominican Republic" },
  { code: "DZ", es: "Argelia", en: "Algeria" },
  { code: "EC", es: "Ecuador", en: "Ecuador" },
  { code: "EE", es: "Estonia", en: "Estonia" },
  { code: "EG", es: "Egipto", en: "Egypt" },
  { code: "ER", es: "Eritrea", en: "Eritrea" },
  { code: "ES", es: "España", en: "Spain" },
  { code: "ET", es: "Etiopía", en: "Ethiopia" },
  { code: "FI", es: "Finlandia", en: "Finland" },
  { code: "FJ", es: "Fiyi", en: "Fiji" },
  { code: "FR", es: "Francia", en: "France" },
  { code: "GA", es: "Gabón", en: "Gabon" },
  { code: "GB", es: "Reino Unido", en: "United Kingdom" },
  { code: "GD", es: "Granada", en: "Grenada" },
  { code: "GE", es: "Georgia", en: "Georgia" },
  { code: "GH", es: "Ghana", en: "Ghana" },
  { code: "GM", es: "Gambia", en: "Gambia" },
  { code: "GN", es: "Guinea", en: "Guinea" },
  { code: "GQ", es: "Guinea Ecuatorial", en: "Equatorial Guinea" },
  { code: "GR", es: "Grecia", en: "Greece" },
  { code: "GT", es: "Guatemala", en: "Guatemala" },
  { code: "GW", es: "Guinea-Bisáu", en: "Guinea-Bissau" },
  { code: "GY", es: "Guyana", en: "Guyana" },
  { code: "HN", es: "Honduras", en: "Honduras" },
  { code: "HR", es: "Croacia", en: "Croatia" },
  { code: "HT", es: "Haití", en: "Haiti" },
  { code: "HU", es: "Hungría", en: "Hungary" },
  { code: "ID", es: "Indonesia", en: "Indonesia" },
  { code: "IE", es: "Irlanda", en: "Ireland" },
  { code: "IL", es: "Israel", en: "Israel" },
  { code: "IN", es: "India", en: "India" },
  { code: "IQ", es: "Irak", en: "Iraq" },
  { code: "IR", es: "Irán", en: "Iran" },
  { code: "IS", es: "Islandia", en: "Iceland" },
  { code: "IT", es: "Italia", en: "Italy" },
  { code: "JM", es: "Jamaica", en: "Jamaica" },
  { code: "JO", es: "Jordania", en: "Jordan" },
  { code: "JP", es: "Japón", en: "Japan" },
  { code: "KE", es: "Kenia", en: "Kenya" },
  { code: "KG", es: "Kirguistán", en: "Kyrgyzstan" },
  { code: "KH", es: "Camboya", en: "Cambodia" },
  { code: "KI", es: "Kiribati", en: "Kiribati" },
  { code: "KM", es: "Comoras", en: "Comoros" },
  { code: "KN", es: "San Cristóbal y Nieves", en: "Saint Kitts and Nevis" },
  { code: "KP", es: "Corea del Norte", en: "North Korea" },
  { code: "KR", es: "Corea del Sur", en: "South Korea" },
  { code: "KW", es: "Kuwait", en: "Kuwait" },
  { code: "KZ", es: "Kazajistán", en: "Kazakhstan" },
  { code: "LA", es: "Laos", en: "Laos" },
  { code: "LB", es: "Líbano", en: "Lebanon" },
  { code: "LC", es: "Santa Lucía", en: "Saint Lucia" },
  { code: "LI", es: "Liechtenstein", en: "Liechtenstein" },
  { code: "LK", es: "Sri Lanka", en: "Sri Lanka" },
  { code: "LR", es: "Liberia", en: "Liberia" },
  { code: "LS", es: "Lesoto", en: "Lesotho" },
  { code: "LT", es: "Lituania", en: "Lithuania" },
  { code: "LU", es: "Luxemburgo", en: "Luxembourg" },
  { code: "LV", es: "Letonia", en: "Latvia" },
  { code: "LY", es: "Libia", en: "Libya" },
  { code: "MA", es: "Marruecos", en: "Morocco" },
  { code: "MC", es: "Mónaco", en: "Monaco" },
  { code: "MD", es: "Moldavia", en: "Moldova" },
  { code: "ME", es: "Montenegro", en: "Montenegro" },
  { code: "MG", es: "Madagascar", en: "Madagascar" },
  { code: "MH", es: "Islas Marshall", en: "Marshall Islands" },
  { code: "MK", es: "Macedonia del Norte", en: "North Macedonia" },
  { code: "ML", es: "Malí", en: "Mali" },
  { code: "MM", es: "Myanmar", en: "Myanmar" },
  { code: "MN", es: "Mongolia", en: "Mongolia" },
  { code: "MR", es: "Mauritania", en: "Mauritania" },
  { code: "MT", es: "Malta", en: "Malta" },
  { code: "MU", es: "Mauricio", en: "Mauritius" },
  { code: "MV", es: "Maldivas", en: "Maldives" },
  { code: "MW", es: "Malaui", en: "Malawi" },
  { code: "MX", es: "México", en: "Mexico" },
  { code: "MY", es: "Malasia", en: "Malaysia" },
  { code: "MZ", es: "Mozambique", en: "Mozambique" },
  { code: "NA", es: "Namibia", en: "Namibia" },
  { code: "NE", es: "Níger", en: "Niger" },
  { code: "NG", es: "Nigeria", en: "Nigeria" },
  { code: "NI", es: "Nicaragua", en: "Nicaragua" },
  { code: "NL", es: "Países Bajos", en: "Netherlands" },
  { code: "NO", es: "Noruega", en: "Norway" },
  { code: "NP", es: "Nepal", en: "Nepal" },
  { code: "NR", es: "Nauru", en: "Nauru" },
  { code: "NZ", es: "Nueva Zelanda", en: "New Zealand" },
  { code: "OM", es: "Omán", en: "Oman" },
  { code: "PA", es: "Panamá", en: "Panama" },
  { code: "PE", es: "Perú", en: "Peru" },
  { code: "PG", es: "Papúa Nueva Guinea", en: "Papua New Guinea" },
  { code: "PH", es: "Filipinas", en: "Philippines" },
  { code: "PK", es: "Pakistán", en: "Pakistan" },
  { code: "PL", es: "Polonia", en: "Poland" },
  { code: "PT", es: "Portugal", en: "Portugal" },
  { code: "PW", es: "Palaos", en: "Palau" },
  { code: "PY", es: "Paraguay", en: "Paraguay" },
  { code: "QA", es: "Catar", en: "Qatar" },
  { code: "RO", es: "Rumanía", en: "Romania" },
  { code: "RS", es: "Serbia", en: "Serbia" },
  { code: "RU", es: "Rusia", en: "Russia" },
  { code: "RW", es: "Ruanda", en: "Rwanda" },
  { code: "SA", es: "Arabia Saudí", en: "Saudi Arabia" },
  { code: "SB", es: "Islas Salomón", en: "Solomon Islands" },
  { code: "SC", es: "Seychelles", en: "Seychelles" },
  { code: "SD", es: "Sudán", en: "Sudan" },
  { code: "SE", es: "Suecia", en: "Sweden" },
  { code: "SG", es: "Singapur", en: "Singapore" },
  { code: "SI", es: "Eslovenia", en: "Slovenia" },
  { code: "SK", es: "Eslovaquia", en: "Slovakia" },
  { code: "SL", es: "Sierra Leona", en: "Sierra Leone" },
  { code: "SM", es: "San Marino", en: "San Marino" },
  { code: "SN", es: "Senegal", en: "Senegal" },
  { code: "SO", es: "Somalia", en: "Somalia" },
  { code: "SR", es: "Surinam", en: "Suriname" },
  { code: "SS", es: "Sudán del Sur", en: "South Sudan" },
  { code: "ST", es: "Santo Tomé y Príncipe", en: "São Tomé and Príncipe" },
  { code: "SV", es: "El Salvador", en: "El Salvador" },
  { code: "SY", es: "Siria", en: "Syria" },
  { code: "SZ", es: "Esuatini", en: "Eswatini" },
  { code: "TD", es: "Chad", en: "Chad" },
  { code: "TG", es: "Togo", en: "Togo" },
  { code: "TH", es: "Tailandia", en: "Thailand" },
  { code: "TJ", es: "Tayikistán", en: "Tajikistan" },
  { code: "TL", es: "Timor Oriental", en: "East Timor" },
  { code: "TM", es: "Turkmenistán", en: "Turkmenistan" },
  { code: "TN", es: "Túnez", en: "Tunisia" },
  { code: "TO", es: "Tonga", en: "Tonga" },
  { code: "TR", es: "Turquía", en: "Turkey" },
  { code: "TT", es: "Trinidad y Tobago", en: "Trinidad and Tobago" },
  { code: "TV", es: "Tuvalu", en: "Tuvalu" },
  { code: "TZ", es: "Tanzania", en: "Tanzania" },
  { code: "UA", es: "Ucrania", en: "Ukraine" },
  { code: "UG", es: "Uganda", en: "Uganda" },
  { code: "US", es: "Estados Unidos", en: "United States" },
  { code: "UY", es: "Uruguay", en: "Uruguay" },
  { code: "UZ", es: "Uzbekistán", en: "Uzbekistan" },
  { code: "VA", es: "Vaticano", en: "Vatican City" },
  { code: "VC", es: "San Vicente y las Granadinas", en: "Saint Vincent and the Grenadines" },
  { code: "VE", es: "Venezuela", en: "Venezuela" },
  { code: "VN", es: "Vietnam", en: "Vietnam" },
  { code: "VU", es: "Vanuatu", en: "Vanuatu" },
  { code: "WS", es: "Samoa", en: "Samoa" },
  { code: "YE", es: "Yemen", en: "Yemen" },
  { code: "ZA", es: "Sudáfrica", en: "South Africa" },
  { code: "ZM", es: "Zambia", en: "Zambia" },
  { code: "ZW", es: "Zimbabue", en: "Zimbabwe" },
];

export function flagEmoji(code: string): string {
  return code
    .toUpperCase()
    .split("")
    .map((c) => String.fromCodePoint(c.charCodeAt(0) + 127397))
    .join("");
}

export function countryName(code: string, locale: "es" | "en"): string {
  const country = COUNTRIES.find((c) => c.code === code.toUpperCase());
  if (!country) return code;
  return locale === "es" ? country.es : country.en;
}
